### PR TITLE
use parameter

### PR DESCRIPTION
**Pull request by yaxu**

### CODE REVIEW

**Comment by ndr-brt** [comment]
As a "command line convention" I think it would be cleaner use "kebab case" like `history-file` instead of `historyFile`

**Comment by yaxu** [comment]
> As a "command line convention" I think it would be cleaner use "kebab case" like `history-file` instead of `historyFile`

Yes agreed and I wanted to do that - but I used camelCase though because history-file isn't valid as a haskell identifier - but I guess there's a way around that?

**Comment by yaxu** [comment]
Ah it seems it automatically converts from kebab to camel case? This module is truly magic.. Fixed!

**Comment by ndr-brt** [comment]
woa!

**Pull request merged**
